#!/bin/bash
# HTTPie command to reproduce this request
# Original URL: https://api.airdna.co/api/explorer/v1/rentalizer/estimate/full
# Method: POST
# Status: 200

http \
  POST \
  https://api.airdna.co/api/explorer/v1/rentalizer/estimate/full \
  sec-ch-ua-platform:"\"macOS\"" \
  authorization:"Bearer TOKEN_HERE" \
  sec-ch-ua:"\"Not)A;Brand\";v=\"8\", \"Chromium\";v=\"138\"" \
  sec-ch-ua-mobile:"?0" \
  user-agent:"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" \
  accept:"application/json" \
  dnt:"1" \
  content-type:"application/json" \
  origin:"https://app.airdna.co" \
  sec-fetch-site:"same-site" \
  sec-fetch-mode:"cors" \
  sec-fetch-dest:"empty" \
  referer:"https://app.airdna.co/" \
  accept-language:"en-US,en;q=0.9" \
  cookie:"[COOKIE_HERE]" \
  '{"currency":"usd","address":"107 Overlook Road, Woodbourne, NY, USA","compute_amenity_percentages":true,"currency_conversion":"use_most_recent_rate"}'
